<?php

namespace Services;

use GuzzleHttp\Client;
use Core\Logger;

class VirtualAccountService
{
    protected Client $client;

        public function __construct()
            {
                    $this->client = new Client([
                                'timeout' => 30
                                        ]);
                                            }

                                                /**
                                                     * Create Reserved Account
                                                          */
                                                              public function create(array $data)
                                                                  {
                                                                          switch (strtolower($data['provider'])) {

                                                                                      case 'billstack':
                                                                                                      return $this->billstack($data);

                                                                                                                  case 'moniepoint':
                                                                                                                                  return $this->moniepoint($data);

                                                                                                                                              case 'payvessel':
                                                                                                                                                              return $this->payvessel($data);

                                                                                                                                                                          case 'paymentpoint':
                                                                                                                                                                                          return $this->paymentpoint($data);

                                                                                                                                                                                                      default:
                                                                                                                                                                                                                      return [
                                                                                                                                                                                                                                          "success"=>false,
                                                                                                                                                                                                                                                              "message"=>"Provider not supported"
                                                                                                                                                                                                                                                                              ];
                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                              private function billstack($data)
                                                                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                                                                          Logger::write("BillStack Reserved Account Request");

                                                                                                                                                                                                                                                                                                                  return [
                                                                                                                                                                                                                                                                                                                              "success"=>false,
                                                                                                                                                                                                                                                                                                                                          "message"=>"BillStack integration pending"
                                                                                                                                                                                                                                                                                                                                                  ];
                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                          private function moniepoint($data)
                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                      Logger::write("Moniepoint Reserved Account Request");

                                                                                                                                                                                                                                                                                                                                                                              return [
                                                                                                                                                                                                                                                                                                                                                                                          "success"=>false,
                                                                                                                                                                                                                                                                                                                                                                                                      "message"=>"Moniepoint integration pending"
                                                                                                                                                                                                                                                                                                                                                                                                              ];
                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                      private function payvessel($data)
                                                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                                                                  Logger::write("PayVessel Reserved Account Request");

                                                                                                                                                                                                                                                                                                                                                                                                                                          return [
                                                                                                                                                                                                                                                                                                                                                                                                                                                      "success"=>false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "message"=>"PayVessel integration pending"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  private function paymentpoint($data)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Logger::write("PaymentPoint Reserved Account Request");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "success"=>false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "message"=>"PaymentPoint integration pending"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }