<?php

namespace Controllers;

use Core\Request;
use Core\Response;
use Core\Validator;
use Models\User;
use Services\JWTService;

class AuthController
{
    private User $user;
        private JWTService $jwt;

            public function __construct()
                {
                        $this->user = new User();
                                $this->jwt = new JWTService();
                                    }

                                        public function register()
                                            {
                                                    $data = Request::body();

                                                            $validator = new Validator();

                                                                    $validator
                                                                                ->required($data, [
                                                                                                'firstname',
                                                                                                                'lastname',
                                                                                                                                'email',
                                                                                                                                                'phone',
                                                                                                                                                                'password',
                                                                                                                                                                                'state'
                                                                                                                                                                                            ])
                                                                                                                                                                                                        ->email('email', $data['email'] ?? '')
                                                                                                                                                                                                                    ->min('password', $data['password'] ?? '', 6);

                                                                                                                                                                                                                            if (!$validator->passes()) {
                                                                                                                                                                                                                                        Response::json([
                                                                                                                                                                                                                                                        'status' => false,
                                                                                                                                                                                                                                                                        'errors' => $validator->errors()
                                                                                                                                                                                                                                                                                    ], 422);
                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                    if ($this->user->findByEmail($data['email'])) {
                                                                                                                                                                                                                                                                                                                Response::json([
                                                                                                                                                                                                                                                                                                                                'status' => false,
                                                                                                                                                                                                                                                                                                                                                'message' => 'Email already exists'
                                                                                                                                                                                                                                                                                                                                                            ], 409);
                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                            if ($this->user->findByPhone($data['phone'])) {
                                                                                                                                                                                                                                                                                                                                                                                        Response::json([
                                                                                                                                                                                                                                                                                                                                                                                                        'status' => false,
                                                                                                                                                                                                                                                                                                                                                                                                                        'message' => 'Phone number already exists'
                                                                                                                                                                                                                                                                                                                                                                                                                                    ], 409);
                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                    $this->user->create($data);

                                                                                                                                                                                                                                                                                                                                                                                                                                                            Response::json([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'status' => true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'message' => 'Registration successful'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    public function login()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $data = Request::body();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $validator = new Validator();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $validator->required($data, [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'email',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'password'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!$validator->passes()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Response::json([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'status' => false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'errors' => $validator->errors()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ], 422);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $user = $this->user->findByEmail($data['email']);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!$user) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Response::json([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'status' => false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'message' => 'Invalid login credentials'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ], 401);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!password_verify($data['password'], $user['sPass'])) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Response::json([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'status' => false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'message' => 'Invalid login credentials'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ], 401);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $this->user->updateLastActivity($user['sId']);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $token = $this->jwt->generate($user);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Response::json([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'status' => true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'token' => $token,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'user' => [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'id' => $user['sId'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'firstname' => $user['sFname'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'lastname' => $user['sLname'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'email' => $user['sEmail'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'phone' => $user['sPhone'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'wallet' => $user['sWallet']
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public function profile()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Response::json([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'status' => true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'message' => 'Profile endpoint is ready'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }