<?php

namespace Models;

use Core\Database;
use PDO;

class User
{
    protected PDO $db;

        public function __construct()
            {
                    $this->db = Database::connection();
                        }

                            public function findByEmail(string $email)
                                {
                                        $stmt = $this->db->prepare(
                                                    "SELECT * FROM subscribers WHERE sEmail = ? LIMIT 1"
                                                            );

                                                                    $stmt->execute([$email]);

                                                                            return $stmt->fetch();
                                                                                }

                                                                                    public function findByPhone(string $phone)
                                                                                        {
                                                                                                $stmt = $this->db->prepare(
                                                                                                            "SELECT * FROM subscribers WHERE sPhone = ? LIMIT 1"
                                                                                                                    );

                                                                                                                            $stmt->execute([$phone]);

                                                                                                                                    return $stmt->fetch();
                                                                                                                                        }

                                                                                                                                            public function findById(int $id)
                                                                                                                                                {
                                                                                                                                                        $stmt = $this->db->prepare(
                                                                                                                                                                    "SELECT * FROM subscribers WHERE sId = ? LIMIT 1"
                                                                                                                                                                            );

                                                                                                                                                                                    $stmt->execute([$id]);

                                                                                                                                                                                            return $stmt->fetch();
                                                                                                                                                                                                }

                                                                                                                                                                                                    public function create(array $data)
                                                                                                                                                                                                        {
                                                                                                                                                                                                                $stmt = $this->db->prepare("
                                                                                                                                                                                                                            INSERT INTO subscribers
                                                                                                                                                                                                                                        (
                                                                                                                                                                                                                                                        sFname,
                                                                                                                                                                                                                                                                        sLname,
                                                                                                                                                                                                                                                                                        sPhone,
                                                                                                                                                                                                                                                                                                        sEmail,
                                                                                                                                                                                                                                                                                                                        sPass,
                                                                                                                                                                                                                                                                                                                                        sState,
                                                                                                                                                                                                                                                                                                                                                        sType,
                                                                                                                                                                                                                                                                                                                                                                        sWallet
                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                VALUES
                                                                                                                                                                                                                                                                                                                                                                                                            (
                                                                                                                                                                                                                                                                                                                                                                                                                            ?,?,?,?,?,?,?,?
                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                ");

                                                                                                                                                                                                                                                                                                                                                                                                                                                        return $stmt->execute([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $data['firstname'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $data['lastname'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $data['phone'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $data['email'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    password_hash($data['password'], PASSWORD_BCRYPT),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $data['state'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public function updateLastActivity(int $id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $stmt = $this->db->prepare("
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                UPDATE subscribers
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            SET sLastActivity = NOW()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        WHERE sId = ?
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return $stmt->execute([$id]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }