<?php

namespace Models;

use Core\Database;
use PDO;

class Withdrawal
{
    protected PDO $db;

        public function __construct()
            {
                    $this->db = Database::connection();
                        }

                            public function create(array $data)
                                {
                                        $stmt = $this->db->prepare("
                                                    INSERT INTO withdrawals
                                                                (
                                                                                sid,
                                                                                                reference,
                                                                                                                account_name,
                                                                                                                                account_number,
                                                                                                                                                bank_code,
                                                                                                                                                                bank_name,
                                                                                                                                                                                amount,
                                                                                                                                                                                                charge,
                                                                                                                                                                                                                status,
                                                                                                                                                                                                                                provider,
                                                                                                                                                                                                                                                narration
                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                        VALUES
                                                                                                                                                                                                                                                                                    (
                                                                                                                                                                                                                                                                                                    ?,?,?,?,?,?,?,?,?,?,?
                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                        ");

                                                                                                                                                                                                                                                                                                                                return $stmt->execute([
                                                                                                                                                                                                                                                                                                                                            $data['sid'],
                                                                                                                                                                                                                                                                                                                                                        $data['reference'],
                                                                                                                                                                                                                                                                                                                                                                    $data['account_name'],
                                                                                                                                                                                                                                                                                                                                                                                $data['account_number'],
                                                                                                                                                                                                                                                                                                                                                                                            $data['bank_code'],
                                                                                                                                                                                                                                                                                                                                                                                                        $data['bank_name'],
                                                                                                                                                                                                                                                                                                                                                                                                                    $data['amount'],
                                                                                                                                                                                                                                                                                                                                                                                                                                $data['charge'],
                                                                                                                                                                                                                                                                                                                                                                                                                                            $data['status'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                        $data['provider'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $data['narration']
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    public function history($sid)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $stmt = $this->db->prepare("
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            SELECT *
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        FROM withdrawals
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    WHERE sid=?
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ORDER BY id DESC
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $stmt->execute([$sid]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return $stmt->fetchAll();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }